page = 18
namespace = 'Settings'
xmlns = 'settings'

[[tags]]
token = 5
name = 'Settings'

[[tags]]
token = 6
name = 'Status'

[[tags]]
token = 7
name = 'Get'

[[tags]]
token = 8
name = 'Set'

[[tags]]
token = 9
name = 'Oof'

[[tags]]
token = 10
name = 'OofState'

[[tags]]
token = 11
name = 'StartTime'

[[tags]]
token = 12
name = 'EndTime'

[[tags]]
token = 13
name = 'OofMessage'

[[tags]]
token = 14
name = 'AppliesToInternal'

[[tags]]
token = 15
name = 'AppliesToExternalKnown'

[[tags]]
token = 16
name = 'AppliesToExternalUnknown'

[[tags]]
token = 17
name = 'Enabled'

[[tags]]
token = 18
name = 'ReplyMessage'

[[tags]]
token = 19
name = 'BodyType'

[[tags]]
token = 20
name = 'DevicePassword'

[[tags]]
token = 21
name = 'Password'

[[tags]]
token = 22
name = 'DeviceInformation'

[[tags]]
token = 23
name = 'Model'

[[tags]]
token = 24
name = 'IMEI'

[[tags]]
token = 25
name = 'FriendlyName'

[[tags]]
token = 26
name = 'OS'

[[tags]]
token = 27
name = 'OSLanguage'

[[tags]]
token = 28
name = 'PhoneNumber'

[[tags]]
token = 29
name = 'UserInformation'

[[tags]]
token = 30
name = 'EmailAddresses'

[[tags]]
token = 31
name = 'SMTPAddress'

[[tags]]
token = 32
name = 'UserAgent'

[[tags]]
token = 33
name = 'EnableOutboundSMS'

[[tags]]
token = 34
name = 'MobileOperator'

[[tags]]
token = 35
name = 'PrimarySmtpAddress'

[[tags]]
token = 36
name = 'Accounts'

[[tags]]
token = 37
name = 'Account'

[[tags]]
token = 38
name = 'AccountId'

[[tags]]
token = 39
name = 'AccountName'

[[tags]]
token = 40
name = 'UserDisplayName'

[[tags]]
token = 41
name = 'SendDisabled'

[[tags]]
token = 43
name = 'RightsManagementInformation'
